coffee_shop:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: aec-2022-02-thursdays # or -thursdays, depending on your cohort
      schema: dbt_hannah-parker # Adjust this to dbt_<your_github_username>.
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
  target: dev
