version: 2

models:
  - name: customers
    description: '{{ doc("customer_doc") }}'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          
  - name: monthly_customers
    description: 'aggregate number of customers by month'
    columns:
      - name: month
        tests:
          - unique
          - not_null          
      - name: customers
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned']             